<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Carbon\Carbon;

class PelangganSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pelanggans')->insert([
            [
                'id' => Str::uuid(),
                'nama' => 'Budi Santoso',
                'jenis_kelamin' => 'Laki-laki',
                'no_ktp' => '7371010101010001',
                'telepon' => '081234500001',
                'email' => 'budi@example.com',
                'alamat' => 'Jl. Merpati No.1, Bandung',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1985-07-10',
                'pekerjaan' => 'Guru',
                'status_perkawinan' => 'Menikah',
                'tipe' => 'Perorangan',
                'npwp' => '73.000.123.4-567.890',
                'foto_ktp' => null,
                'foto_npwp' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Siti Aminah',
                'jenis_kelamin' => 'Perempuan',
                'no_ktp' => '7371020202020002',
                'telepon' => '082134500002',
                'email' => 'siti@example.com',
                'alamat' => 'Jl. Melati No.2, Yogyakarta',
                'tempat_lahir' => 'Yogyakarta',
                'tanggal_lahir' => '1992-03-25',
                'pekerjaan' => 'Dokter',
                'status_perkawinan' => 'Belum Menikah',
                'tipe' => 'Perorangan',
                'npwp' => '73.001.234.5-678.901',
                'foto_ktp' => null,
                'foto_npwp' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Rudi Hartono',
                'jenis_kelamin' => 'Laki-laki',
                'no_ktp' => '7371030303030003',
                'telepon' => '083154500003',
                'email' => 'rudi@example.com',
                'alamat' => 'Jl. Kenanga No.3, Surabaya',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '1980-11-15',
                'pekerjaan' => 'Pengusaha',
                'status_perkawinan' => 'Menikah',
                'tipe' => 'Perorangan',
                'npwp' => '73.002.345.6-789.012',
                'foto_ktp' => null,
                'foto_npwp' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'PT Maju Sejahtera',
                'jenis_kelamin' => null,
                'no_ktp' => '0000000000000001',
                'telepon' => '02187654321',
                'email' => 'admin@maju.co.id',
                'alamat' => 'Jl. Sudirman No.88, Jakarta',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'pekerjaan' => null,
                'status_perkawinan' => null,
                'tipe' => 'Perusahaan',
                'npwp' => '01.111.111.1-111.000',
                'foto_ktp' => null,
                'foto_npwp' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'CV Sumber Rezeki',
                'jenis_kelamin' => null,
                'no_ktp' => '0000000000000002',
                'telepon' => '0271123456',
                'email' => 'contact@sumberrezeki.co.id',
                'alamat' => 'Jl. Kaliurang No.77, Sleman',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'pekerjaan' => null,
                'status_perkawinan' => null,
                'tipe' => 'Perusahaan',
                'npwp' => '02.222.222.2-222.000',
                'foto_ktp' => null,
                'foto_npwp' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Dewi Lestari',
                'jenis_kelamin' => 'Perempuan',
                'no_ktp' => '7371040404040004',
                'telepon' => '081244400004',
                'email' => 'dewi@example.com',
                'alamat' => 'Jl. Sakura No.4, Semarang',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '1995-12-01',
                'pekerjaan' => 'Desainer',
                'status_perkawinan' => 'Belum Menikah',
                'tipe' => 'Perorangan',
                'npwp' => '73.003.456.7-890.123',
                'foto_ktp' => null,
                'foto_npwp' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Andika Putra',
                'jenis_kelamin' => 'Laki-laki',
                'no_ktp' => '7371050505050005',
                'telepon' => '081255500005',
                'email' => 'andika@example.com',
                'alamat' => 'Jl. Anggrek No.5, Denpasar',
                'tempat_lahir' => 'Denpasar',
                'tanggal_lahir' => '1988-08-21',
                'pekerjaan' => 'Arsitek',
                'status_perkawinan' => 'Menikah',
                'tipe' => 'Perorangan',
                'npwp' => '73.004.567.8-901.234',
                'foto_ktp' => null,
                'foto_npwp' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'PT Bangun Cipta',
                'jenis_kelamin' => null,
                'no_ktp' => '0000000000000003',
                'telepon' => '0215678910',
                'email' => 'info@banguncipta.com',
                'alamat' => 'Jl. Rasuna Said No.10, Jakarta',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'pekerjaan' => null,
                'status_perkawinan' => null,
                'tipe' => 'Perusahaan',
                'npwp' => '03.333.333.3-333.000',
                'foto_ktp' => null,
                'foto_npwp' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'Rina Marlina',
                'jenis_kelamin' => 'Perempuan',
                'no_ktp' => '7371060606060006',
                'telepon' => '082166600006',
                'email' => 'rina@example.com',
                'alamat' => 'Jl. Cemara No.6, Medan',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '1993-09-09',
                'pekerjaan' => 'Notaris',
                'status_perkawinan' => 'Menikah',
                'tipe' => 'Perorangan',
                'npwp' => '73.005.678.9-012.345',
                'foto_ktp' => null,
                'foto_npwp' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'nama' => 'CV Cipta Properti',
                'jenis_kelamin' => null,
                'no_ktp' => '0000000000000004',
                'telepon' => '0341123456',
                'email' => 'cs@ciptaproperti.id',
                'alamat' => 'Jl. Ijen No.9, Malang',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'pekerjaan' => null,
                'status_perkawinan' => null,
                'tipe' => 'Perusahaan',
                'npwp' => '04.444.444.4-444.000',
                'foto_ktp' => null,
                'foto_npwp' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
