<?php

namespace Database\Seeders;

use App\Models\Properti;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\MasterWilayah;
use Carbon\Carbon;

class PropertiSeeder extends Seeder
{

    public function run(): void
    {
        DB::table('propertis')->delete();

        $data = [
            [
                'id' => '0198a628-2a21-71be-9b4f-8e6968d69c2f',
                'judul' => 'New Blossom - Virginia Park Hunian Modern & Strategis Dekat Bandara dan Tol',
                'slug' => 'new-blossom-virginia-park-hunian-modern-strategis-dekat-bandara-dan-tol',
                'jenis_properti_id' => 'a6023ab6-4e6e-4add-b2aa-9ef2e39e2bfa',
                'deskripsi' => '<p>New Blossom - Virginia Park Hunian Modern &amp; Strategis. Temukan hunian impian Anda di Virginia Park Makassar. Lokasi strategis dekat Bandara, Tol, dan Stasiun KA. Nikmati fasilitas lengkap, desain modern tropis, dan lingkungan hijau. Tersedia berbagai tipe unit dengan&nbsp;promo&nbsp;menarik.</p><p><br></p><p><br></p>',
                'harga' => 600000000.00,
                'status' => 'Tersedia',
                'penawaran' => 'Dijual',
                'jenis_cluster' => 'Blossom',
                'tipe_perumahan' => 'New Blossom',
                'provinsi' => '73',
                'kabupaten' => '73.71',
                'kecamatan' => '73.71.11',
                'kelurahan' => '73.71.11.1004',
                'kode_pos' => '90242',
                'link_brosur' => '#',
                'link_layout' => '#',
                'link_spesifikasi' => '#',
                'link_site_plan' => '#',
                'gbr_primary_properti' => 'data-pendukung/01K2K2GAGRA7K5DATGKBF95SCT.webp',
                'alamat_lengkap' => 'Jl. Ir. Sutami No.20',
                'jumlah_kamar_tidur' => 3,
                'jumlah_kamar_mandi' => 2,
                'luas_bangunan' => 72,
                'luas_tanah' => 73,
                'tahun_dibangun' => 2025,
                'unggulan' => false,
                'created_at' => '2025-08-14 01:18:26',
                'updated_at' => '2025-08-14 01:27:10'
            ],
            [
                'id' => '0198e90b-4217-713c-b42a-6a7a6124315c',
                'judul' => 'XYZ X5 / X7 Livin hunian viral yang berlokasi strategis di Green River View, Tanjung Bunga',
                'slug' => 'xyz-x5-x7-livin-hunian-viral-yang-berlokasi-strategis-di-green-river-view-tanjung-bunga',
                'jenis_properti_id' => 'a6023ab6-4e6e-4add-b2aa-9ef2e39e2bfa',
                'deskripsi' => '<p>XYZ Livin – Hunian Modern di Kawasan Premium Tanjung Bunga<br><br>XYZ Livin menghadirkan konsep hunian modern yang dirancang untuk keluarga dinamis yang mengutamakan kenyamanan, keamanan, dan gaya hidup praktis. Terletak di kawasan prestisius Tanjung Bunga, Makassar, cluster ini menawarkan akses mudah ke pusat kota, pusat perbelanjaan, sekolah, hingga kawasan rekreasi tepi laut.<br><br>Dengan desain arsitektur kontemporer yang elegan, setiap unit di XYZ Livin memaksimalkan pencahayaan alami dan sirkulasi udara yang sehat, menciptakan suasana rumah yang hangat dan nyaman.<br><br>Keunggulan XYZ Livin<br><br>Lokasi strategis di kawasan berkembang Tanjung Bunga<br><br>Desain rumah modern minimalis dengan tata ruang fungsional<br><br>Lingkungan aman dengan sistem keamanan 24 jam<br><br>Fasilitas pendukung untuk menunjang gaya hidup modern<br><br>Akses dekat ke mall, sekolah, rumah sakit, dan waterfront city<br><br><br>Mengapa Memilih XYZ Livin?<br><br>Hunian ini bukan sekadar tempat tinggal, melainkan investasi bernilai tinggi di kawasan premium. XYZ Livin dirancang untuk memberikan keseimbangan antara kehidupan keluarga yang harmonis dan kemudahan akses menuju pusat aktivitas kota.<br><br>✨ Wujudkan impian memiliki rumah modern di kawasan prestisius Tanjung Bunga bersama Anima Properti – partner terpercaya Anda dalam menemukan&nbsp;hunian&nbsp;terbaik.</p>',
                'harga' => 643000000.00,
                'status' => 'Tersedia',
                'penawaran' => 'Dijual',
                'jenis_cluster' => 'XYZ Livin',
                'tipe_perumahan' => 'Tipe X7',
                'provinsi' => '73',
                'kabupaten' => '73.71',
                'kecamatan' => '73.71.10',
                'kelurahan' => '73.71.10.1010',
                'kode_pos' => '90134',
                'link_brosur' => '#',
                'link_layout' => '#',
                'link_spesifikasi' => '#',
                'link_site_plan' => '#',
                'gbr_primary_properti' => 'data-pendukung/01K3MGPGFX67TF1HKAKK77VSW3.webp',
                'alamat_lengkap' => 'Jl. Metro Tanjung Bunga',
                'jumlah_kamar_tidur' => 3,
                'jumlah_kamar_mandi' => 2,
                'luas_bangunan' => 63,
                'luas_tanah' => 65,
                'tahun_dibangun' => 2025,
                'unggulan' => false,
                'created_at' => '2025-08-27 01:01:25',
                'updated_at' => '2025-08-27 01:01:58'
            ],
            [
                'id' => '0198e92a-db3c-72dc-843d-bd140094d907',
                'judul' => 'Rumah Secondary di Perum Dosen UMI Tipe 54',
                'slug' => 'rumah-secondary-di-perum-dosen-umi-tipe-54',
                'jenis_properti_id' => 'a6023ab6-4e6e-4add-b2aa-9ef2e39e2bfa',
                'deskripsi' => '<p>Rumah Second Dijual – Perumahan Dosen UMI, Blok M4 No.1, Rama Sejahtera, Makassar<br><br>Temukan hunian nyaman untuk keluarga Anda di Perumahan Dosen UMI, Makassar. Rumah second ini berada di lokasi strategis dengan lingkungan yang sudah tertata rapi dan akses mudah ke berbagai fasilitas umum.<br><br>Dengan ukuran tanah 9 x 13 m dan tipe bangunan 54, rumah ini memiliki ruang yang cukup luas untuk menunjang aktivitas keluarga. Cocok untuk Anda yang mencari hunian dekat sekolah, fasilitas kesehatan, maupun pusat aktivitas kota.<br><br>Spesifikasi Rumah:<br><br>Luas tanah: 117 m² (9 x 13)<br>Luas bangunan: 54 m²<br>Kamar tidur: 4<br>Kamar mandi: 1<br>Ruang tamu &amp; ruang keluarga<br>Dapur &amp; area belakang<br><br>Lokasi: Perumahan Dosen UMI Blok M4 No.1, Rama Sejahtera, Makassar<br><br><br>Keunggulan Lokasi:<br><br>Dekat sekolah dan kampus UMI<br>Lingkungan perumahan tertata &amp; nyaman<br>Akses mudah ke pasar, rumah sakit, dan pusat perbelanjaan<br>Jalan kompleks lebar &amp; akses kendaraan lancar<br><br><br>✨ Hunian ini sangat cocok untuk keluarga yang mengutamakan kenyamanan, keamanan, dan lokasi strategis di kota Makassar.</p>',
                'harga' => 1400000000.00,
                'status' => 'Tersedia',
                'penawaran' => 'Dijual',
                'jenis_cluster' => 'Dosen Umi',
                'tipe_perumahan' => '54',
                'provinsi' => '73',
                'kabupaten' => '73.71',
                'kecamatan' => '73.71.09',
                'kelurahan' => '73.71.09.1005',
                'kode_pos' => '90231',
                'link_brosur' => '#',
                'link_layout' => '#',
                'link_spesifikasi' => '#',
                'link_site_plan' => '#',
                'gbr_primary_properti' => 'data-pendukung/01K3MJNPS8P7YYK5HXA5989SSS.jpg',
                'alamat_lengkap' => 'jl. racing centre makassar',
                'jumlah_kamar_tidur' => 4,
                'jumlah_kamar_mandi' => 2,
                'luas_bangunan' => 100,
                'luas_tanah' => 117,
                'tahun_dibangun' => 2020,
                'unggulan' => false,
                'created_at' => '2025-08-27 01:35:56',
                'updated_at' => '2025-08-27 01:38:53'
            ],
            [
                'id' => '0198e942-44a8-73a3-9d91-94559bc33471',
                'judul' => 'Rumah Mewah Dijual – Citraland Celebes Makassar',
                'slug' => 'rumah-mewah-dijual-citraland-celebes-makassar',
                'jenis_properti_id' => 'a6023ab6-4e6e-4add-b2aa-9ef2e39e2bfa',
                'deskripsi' => '<p>Rumah Second Dijual – Citraland Celebes Makassar<br><br>Hunian mewah dan nyaman kini tersedia di kawasan prestisius Citraland Celebes, Makassar. Rumah dua lantai ini dirancang dengan gaya modern yang elegan, lengkap dengan furnitur pilihan sehingga siap langsung dihuni tanpa perlu renovasi besar.<br><br>Dengan ukuran tanah 9 x 18 m dan bangunan seluas 130 m², rumah ini memberikan ruang yang lega bagi seluruh anggota keluarga. Setiap detail desain menghadirkan kenyamanan serta kesan eksklusif khas kawasan premium Citraland.<br><br>Spesifikasi Rumah:<br><br>Luas tanah: 162 m² (9 x 18)<br>Luas bangunan: 130 m²<br>Jumlah lantai: 2<br>Kamar tidur: 3<br>Kamar mandi: 3<br>Garasi<br><br>Furnished / sudah dilengkapi perabotan<br><br><br>Keunggulan Lokasi &amp; Lingkungan:<br><br>Berada di kawasan premium Citraland Celebes Makassar<br>Lingkungan perumahan modern, bersih, dan aman<br>Fasilitas lengkap: taman, area hijau, keamanan 24 jam<br>Akses strategis menuju pusat kota, sekolah, rumah sakit, dan pusat perbelanjaan<br><br><br>✨ Kesempatan istimewa memiliki hunian elegan di Citraland Celebes Makassar . Rumah ini siap huni, nyaman, dan bernilai investasi tinggi.</p>',
                'harga' => 2600000000.00,
                'status' => 'Tersedia',
                'penawaran' => 'Dijual',
                'jenis_cluster' => 'Citraland',
                'tipe_perumahan' => 'Backyard',
                'provinsi' => '73',
                'kabupaten' => '73.06',
                'kecamatan' => '73.06.08',
                'kelurahan' => '73.06.08.1008',
                'kode_pos' => '90233',
                'link_brosur' => '#',
                'link_layout' => '#',
                'link_spesifikasi' => '#',
                'link_site_plan' => '#',
                'gbr_primary_properti' => 'data-pendukung/01K3MM4H4Y1T754VPJFZ65PYWH.jpeg',
                'alamat_lengkap' => 'Jl. Tun Abdul Razak Citraland Celebes',
                'jumlah_kamar_tidur' => 3,
                'jumlah_kamar_mandi' => 3,
                'luas_bangunan' => 162,
                'luas_tanah' => 130,
                'tahun_dibangun' => 2020,
                'unggulan' => false,
                'created_at' => '2025-08-27 02:01:31',
                'updated_at' => '2025-08-27 02:02:00'
            ],
            [
                'id' => '0198e94f-6c54-7257-a342-9d3c26aac202',
                'judul' => 'Tanah di Daya dekat Jl. Paccerekang dan Jl. Berua Raya',
                'slug' => 'tanah-di-daya-dekat-jl-paccerekang-dan-jl-berua-raya',
                'jenis_properti_id' => 'e16734bc-b47b-4bf0-b5a8-08f2f273bf11',
                'deskripsi' => '<p>Tanah Dijual – Jl. Berua 1A, Daya, Makassar<br><br>Kesempatan memiliki lahan strategis di Jl. Berua 1A, Daya – Makassar. Berada di kawasan berkembang dengan akses mudah menuju jalan utama, area permukiman, dan pusat aktivitas harian, lahan ini cocok untuk hunian, kos-kosan, ruko kecil, hingga investasi jangka panjang.<br><br>Keunggulan Lokasi<br><br>Akses dekat ke fasilitas pendidikan, pasar, layanan kesehatan, dan area komersial<br>Lingkungan sekitar ramai penduduk, prospektif untuk usaha<br>Kontur lahan siap bangun (ideal untuk pengembangan cepat)<br><br><br>Potensi Penggunaan<br>Rumah tinggal / kavling keluarga<br>Kos-kosan atau kontrakan (demand tinggi di kawasan padat)<br>Ruko kecil/usaha rumahan<br>Investasi lahan untuk capital gain di koridor Daya<br><br><br>Nilai Tambah<br>Jalan lingkungan dapat dilalui kendaraan<br>Bentuk lahan memudahkan penataan bangunan<br>Legalitas siap dicek dan dibantu prosesnya oleh Anima Properti<br><br><br>✨ Pilihan tepat untuk Anda yang mencari tanah dengan lokasi jelas, akses mudah, dan prospek usaha/hunian di Daya, Makassar.<br>Hubungi Anima Properti untuk info luas, harga, dan jadwal survei lokasi.</p>',
                'harga' => 500000000.00,
                'status' => 'Tersedia',
                'penawaran' => 'Dijual',
                'jenis_cluster' => '#',
                'tipe_perumahan' => '#',
                'provinsi' => '73',
                'kabupaten' => '73.71',
                'kecamatan' => '73.71.11',
                'kelurahan' => '73.71.11.1002',
                'kode_pos' => '90241',
                'link_brosur' => '#',
                'link_layout' => '#',
                'link_spesifikasi' => '#',
                'link_site_plan' => '#',
                'gbr_primary_properti' => 'data-pendukung/01K3MMYV2AWSPDXMPB3XMCJ21Q.webp',
                'alamat_lengkap' => 'jl. Berua 1 A Daya',
                'jumlah_kamar_tidur' => 0,
                'jumlah_kamar_mandi' => 0,
                'luas_bangunan' => 0,
                'luas_tanah' => 200,
                'tahun_dibangun' => NULL,
                'unggulan' => false,
                'created_at' => '2025-08-27 02:15:53',
                'updated_at' => '2025-08-27 02:17:02'
            ],
            [
                'id' => '0198e962-51e0-70a7-84cc-15cd3591baf4',
                'judul' => 'Rumah Secondary Dijual – Citraland Celebes, Cluster Golden Garnet Xaviera H2',
                'slug' => 'rumah-secondary-dijual-citraland-celebes-cluster-golden-garnet-xaviera-h2',
                'jenis_properti_id' => 'a6023ab6-4e6e-4add-b2aa-9ef2e39e2bfa',
                'deskripsi' => '<p>Temukan hunian eksklusif di kawasan prestisius Citraland Celebes Makassar. Rumah secondary 2 lantai ini berlokasi di Cluster Golden Garnet, Xaviera H2, salah satu area favorit yang mengutamakan kenyamanan, keamanan, dan lingkungan modern.<br><br>Dengan ukuran tanah 7 x 15 m, rumah ini memiliki tata ruang fungsional, dilengkapi 3 kamar tidur dan 3 kamar mandi. Posisi rumah sudut memberikan keunggulan pencahayaan alami lebih banyak, sirkulasi udara sehat, serta halaman lebih luas untuk kenyamanan keluarga.<br><br>Spesifikasi Rumah:<br>Luas tanah: 105 m² (7 x 15)<br>Jumlah lantai: 2<br>Kamar tidur: 3<br>Kamar mandi: 3<br>Posisi rumah sudut (corner unit)<br><br><br>Keunggulan Lokasi &amp; Lingkungan:<br>Berada di kawasan premium dengan keamanan 24 jam<br>Lingkungan modern, bersih, dan nyaman<br>Fasilitas lengkap: taman hijau, area rekreasi, dan jalan lingkungan lebar<br>Lokasi strategis dekat pusat kota, sekolah, rumah sakit, dan area komersial<br><br><br>Harga Pasaran &amp; Value Properti:<br><br>Rumah di Cluster Golden Garnet Citraland Celebes saat ini ditawarkan dengan harga pasaran mulai dari Rp 2,4 M – Rp 3 M, tergantung posisi dan kondisi bangunan.<br><br>✨ Dengan posisi rumah sudut, properti ini memiliki nilai lebih tinggi dan sangat cocok dijadikan hunian keluarga modern sekaligus investasi properti jangka panjang.</p>',
                'harga' => 2200000000.00,
                'status' => 'Tersedia',
                'penawaran' => 'Dijual',
                'jenis_cluster' => 'Golden Garnet',
                'tipe_perumahan' => 'Xaviera',
                'provinsi' => '73',
                'kabupaten' => '73.06',
                'kecamatan' => '73.06.08',
                'kelurahan' => '73.06.08.1008',
                'kode_pos' => '90233',
                'link_brosur' => '#',
                'link_layout' => '#',
                'link_spesifikasi' => '#',
                'link_site_plan' => '#',
                'gbr_primary_properti' => 'data-pendukung/01K3MP4MESXSWQ7JYBWAYSSSG6.jpeg',
                'alamat_lengkap' => 'Jl. Tun Abdul Razak Citraland Celebes',
                'jumlah_kamar_tidur' => 3,
                'jumlah_kamar_mandi' => 3,
                'luas_bangunan' => 90,
                'luas_tanah' => 105,
                'tahun_dibangun' => 2020,
                'unggulan' => false,
                'created_at' => '2025-08-27 02:36:31',
                'updated_at' => '2025-08-27 02:36:31'
            ],
            [
                'id' => '0198eae4-bd2e-733d-beb3-d749677c0d63',
                'judul' => 'Ruko 2 Lantai Dijual – Jl. Minasaupa Poros, 100m dari Jl. Hertasning, Makassar',
                'slug' => 'ruko-2-lantai-dijual-jl-minasaupa-poros-100m-dari-jl-hertasning-makassar',
                'jenis_properti_id' => '8f7087f7-c5ce-4a85-9371-c37ad8784966',
                'deskripsi' => '<p>Kesempatan langka memiliki ruko strategis 2 lantai di kawasan komersial berkembang, Jl. Minasaupa Poros, hanya ±100 meter dari Jl. Hertasning, salah satu jalan utama di Makassar. Lokasi ini sangat cocok untuk berbagai jenis usaha, baik kuliner, kantor, minimarket, maupun investasi jangka panjang.<br><br>Dengan ukuran bangunan 4,5 x 13 m, ruko ini dilengkapi dengan fasilitas penunjang yang membuatnya nyaman sekaligus fungsional.<br><br><br>Keunggulan Lokasi &amp; Potensi:<br>Area ramai dengan lalu lintas tinggi (high traffic)<br>Sangat cocok untuk usaha kuliner, kantor, apotek, klinik, atau minimarket<br>Akses cepat ke kawasan perumahan, sekolah, dan pusat bisnis di Hertasning–Minasaupa<br>Nilai properti terus meningkat seiring pesatnya perkembangan kawasan<br><br><br>✨ Ruko 2 lantai di Minasaupa ini adalah pilihan tepat untuk Anda yang mencari lokasi usaha strategis di Makassar dengan potensi keuntungan tinggi.</p>',
                'harga' => 1500000000.00,
                'status' => 'Tersedia',
                'penawaran' => 'Dijual',
                'jenis_cluster' => 'Ruko',
                'tipe_perumahan' => 'Ruko',
                'provinsi' => '73',
                'kabupaten' => '73.71',
                'kecamatan' => '73.71.13',
                'kelurahan' => '73.71.13.1009',
                'kode_pos' => '90221',
                'link_brosur' => '#',
                'link_layout' => '#',
                'link_spesifikasi' => '#',
                'link_site_plan' => '#',
                'gbr_primary_properti' => 'data-pendukung/01K3NE9F97TV6X45GHD9MX8BV7.jpeg',
                'alamat_lengkap' => 'Jl. Minasaupa Makassar',
                'jumlah_kamar_tidur' => 1,
                'jumlah_kamar_mandi' => 2,
                'luas_bangunan' => 117,
                'luas_tanah' => 59,
                'tahun_dibangun' => 2020,
                'unggulan' => false,
                'created_at' => '2025-08-27 09:38:35',
                'updated_at' => '2025-08-27 09:38:35'
            ],
            [
                'id' => '019994b1-8b10-7212-8e61-9ca5f8004332',
                'judul' => 'Tanah Kaplingan Sudut di Tallasa City',
                'slug' => 'tanah-kaplingan-sudut-di-tallasa-city',
                'jenis_properti_id' => 'e16734bc-b47b-4bf0-b5a8-08f2f273bf11',
                'deskripsi' => '<p>📍 Tanah Sudut Dijual – Greenstone Tallasa City, Citraland Makassar<br><br>✨ Kesempatan langka memiliki tanah sudut strategis di kawasan premium Citraland!<br><br>Luas tanah: 165 m²<br><br>Posisi hook/sudut dengan dua akses jalan<br><br>Cocok untuk bangun rumah mewah, usaha, atau investasi jangka panjang<br><br>Berada di lingkungan modern, aman, dan nyaman<br><br>Akses mudah ke berbagai fasilitas kota, pusat perbelanjaan, sekolah, dan jalan utama<br><br><br>💎 Greenstone Tallasa City dikenal sebagai kawasan hunian prestisius dengan nilai investasi yang terus meningkat.<br><br>Harga menarik &amp; siap nego untuk serius buyer.<br><br>📞 Hubungi sekarang untuk survei lokasi!</p>',
                'harga' => 1500000.00,
                'status' => 'Tersedia',
                'penawaran' => 'Dijual',
                'jenis_cluster' => NULL,
                'tipe_perumahan' => NULL,
                'provinsi' => '73',
                'kabupaten' => '73.71',
                'kecamatan' => '73.71.14',
                'kelurahan' => '73.71.14.1001',
                'kode_pos' => '90245',
                'link_brosur' => '#',
                'link_layout' => '#',
                'link_spesifikasi' => '#',
                'link_site_plan' => '#',
                'gbr_primary_properti' => 'data-pendukung/01K6AB32R0J8SEQJR85XK9MQK9.jpg',
                'alamat_lengkap' => 'Jl. Jalur Lingkaran Barat - Makassar',
                'jumlah_kamar_tidur' => NULL,
                'jumlah_kamar_mandi' => NULL,
                'luas_bangunan' => NULL,
                'luas_tanah' => 165,
                'tahun_dibangun' => NULL,
                'unggulan' => false,
                'created_at' => '2025-09-29 08:58:07',
                'updated_at' => '2025-09-29 08:58:07'
            ],
            [
                'id' => '6bf51334-707c-412e-ba8d-00fdcd39ce79',
                'judul' => 'Cluster Anthura Tallasa City Makassar',
                'slug' => 'cluster-anthura-tallasa-city-makassar',
                'jenis_properti_id' => 'a6023ab6-4e6e-4add-b2aa-9ef2e39e2bfa',
                'deskripsi' => '<p>Cluster Anthura akan mendukung gaya hidup urban tropis di lingkungan yang modern, menghadirkan kehidupan lestari dan bahagia</p><p>Setiap hunian dirancang dengan mengutamakan kenyamanan, keharmonisan, efesiensi serta mendukung mobilitas sekaligus menjaga keselarasan dengan alam. Menjadi pilihan ideal bagi anda yang menginginkan keseimbangan hidup.</p><p>Cluster terbaru di Tallasa City ini menghadirkan hunian premium di Makassar, mengusung desain geometris modern yang harmonis dengan alam. Nama Anthura mempresentasikan keuntungan, keindahan, ketahanan serta kebahagiaan.</p><p>Memiliki pilihan tipe unit 6x12, 6x15, 7x15 dan 8x15.</p>',
                'harga' => 1300000000.00,
                'status' => 'Tersedia',
                'penawaran' => 'Dijual',
                'jenis_cluster' => 'Anthura',
                'tipe_perumahan' => '6x12',
                'provinsi' => '73',
                'kabupaten' => '73.71',
                'kecamatan' => '73.71.14',
                'kelurahan' => '73.71.14.1002',
                'kode_pos' => '90241',
                'link_brosur' => 'https://tallasacitymakassar.com/wp-content/uploads/2025/08/Brosur-Anthura-launching.pdf',
                'link_layout' => '#',
                'link_spesifikasi' => '#',
                'link_site_plan' => '#',
                'gbr_primary_properti' => 'data-pendukung/01K1ZN43K64K1V9TXK1SBCDWD2.webp',
                'alamat_lengkap' => 'Jl. kapasa raya',
                'jumlah_kamar_tidur' => 3,
                'jumlah_kamar_mandi' => 2,
                'luas_bangunan' => 89,
                'luas_tanah' => 72,
                'tahun_dibangun' => 2025,
                'unggulan' => true,
                'created_at' => '2025-08-05 13:28:29',
                'updated_at' => '2025-08-08 10:38:07'
            ],
            [
                'id' => 'a2a77ce3-79d4-4023-a025-b76a534f39c0',
                'judul' => 'Dijual Rumah di Summarecon - Blue Crystal',
                'slug' => 'dijual-rumah-di-summarecon-blue-crystal',
                'jenis_properti_id' => 'a6023ab6-4e6e-4add-b2aa-9ef2e39e2bfa',
                'deskripsi' => '<p>Hunian Modern 2 Lantai di Summarecon Mutiara Makassar</p>',
                'harga' => 1400000000.00,
                'status' => 'Tersedia',
                'penawaran' => 'Dijual',
                'jenis_cluster' => 'A-12',
                'tipe_perumahan' => 'B36',
                'provinsi' => '73',
                'kabupaten' => '73.71',
                'kecamatan' => '73.71.11',
                'kelurahan' => '73.71.11.1004',
                'kode_pos' => '90231',
                'link_brosur' => '-',
                'link_layout' => '-',
                'link_spesifikasi' => '-',
                'link_site_plan' => '-',
                'gbr_primary_properti' => 'data-pendukung/01K249A1MSJGMXXNA9X6YRHHPR.jpg',
                'alamat_lengkap' => 'Jl. Mutiara Boulevard',
                'jumlah_kamar_tidur' => 2,
                'jumlah_kamar_mandi' => 2,
                'luas_bangunan' => 76,
                'luas_tanah' => 112,
                'tahun_dibangun' => 2023,
                'unggulan' => false,
                'created_at' => '2025-08-05 13:28:29',
                'updated_at' => '2025-08-08 10:38:22'
            ],
            [
                'id' => 'f4808f9f-acf6-4288-b4a1-605b9511bb0f',
                'judul' => 'Disewakan Rumah di Summarecon - Blue Crystal',
                'slug' => 'disewakan-rumah-di-summarecon-blue-crystal',
                'jenis_properti_id' => 'a6023ab6-4e6e-4add-b2aa-9ef2e39e2bfa',
                'deskripsi' => '<p>Hunian Modern 2 Lantai di Summarecon Mutiara Makassar</p>',
                'harga' => 60000000.00,
                'status' => 'Tersedia',
                'penawaran' => 'Disewa',
                'jenis_cluster' => 'A-12',
                'tipe_perumahan' => 'B36',
                'provinsi' => '73',
                'kabupaten' => '73.71',
                'kecamatan' => '73.71.11',
                'kelurahan' => '73.71.11.1004',
                'kode_pos' => '90241',
                'link_brosur' => '-',
                'link_layout' => '-',
                'link_spesifikasi' => '-',
                'link_site_plan' => '-',
                'gbr_primary_properti' => 'data-pendukung/01K249DY1PKWZ64YQ4V40A1Z2E.jpg',
                'alamat_lengkap' => 'Jl. Mutiara Boulevard',
                'jumlah_kamar_tidur' => 2,
                'jumlah_kamar_mandi' => 2,
                'luas_bangunan' => 76,
                'luas_tanah' => 112,
                'tahun_dibangun' => 2023,
                'unggulan' => false,
                'created_at' => '2025-08-05 13:28:29',
                'updated_at' => '2025-08-08 10:38:41'
            ],
        ];

        $this->command->info('DEBUG: Inserting Property with ID: ' . $data[0]['id']);
        DB::table('propertis')->insert($data);
    }
}
